### ISSUE TITLE
cannot install mwan3 on this firmware

### ISSUE THREAD

**Issue by rickicode** [amaumene/xiaomi_redmi-router-ac2100_openwrt_mesh#1]
![image](https://user-images.githubusercontent.com/16317768/90974538-82a4ad80-e556-11ea-8e22-fb9b14abdbd1.png)

i think need update kernel

**Comment by amaumene** [comment]
Hi, sorry for my late answer. The daily build process was broken for a few days. I’ve updated it. Please try with the latest version.
